# Generated by Django 6.0.3 on 2026-04-06 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='songrequest',
            old_name='reviewed_at',
            new_name='admin_reviewed_at',
        ),
        migrations.RemoveField(
            model_name='songrequest',
            name='reviewed_by',
        ),
        migrations.AddField(
            model_name='songrequest',
            name='dj_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='reviewed_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_reviewed_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='reviewed_by_dj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dj_reviewed_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='songrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('admin_approved', 'Approved by Admin'), ('admin_rejected', 'Rejected by Admin'), ('dj_approved', 'Approved by DJ'), ('dj_rejected', 'Rejected by DJ'), ('invalid', 'Invalid')], default='pending', max_length=20),
        ),
    ]
