# Generated by Django 6.0.3 on 2026-04-21 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_requests', '0002_rename_reviewed_at_songrequest_admin_reviewed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='songrequest',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_songs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='songrequest',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
