# Generated by Django 6.0.3 on 2026-03-30 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_request_enabled', models.BooleanField(default=True)),
                ('screen_request_enabled', models.BooleanField(default=True)),
                ('menu_enabled', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Club Settings',
            },
        ),
    ]
