# Generated by Django 6.0.3 on 2026-04-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('weekend', 'Weekend')], max_length=10)),
                ('request_type', models.CharField(choices=[('song_request', 'Song Request'), ('running_text', 'Running Text'), ('vtron_text', 'Vtron Text'), ('vtron_photo', 'Vtron Photo'), ('vtron_video', 'Vtron Video')], max_length=20)),
                ('min_amount', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('day_type', 'request_type')},
            },
        ),
    ]
