# Generated by Django 6.0.3 on 2026-03-24 04:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customersession',
            name='invite',
        ),
        migrations.AddField(
            model_name='table',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='table',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.DeleteModel(
            name='TableInvite',
        ),
    ]
