# Generated by Django 6.0.3 on 2026-04-08 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_table_qr_token_tableinvite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customersession',
            name='invite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='tables.tableinvite'),
        ),
    ]
