# Generated by Django 6.0.3 on 2026-04-09 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_customersession_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='customersession',
            name='screen_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customersession',
            name='song_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
