# Generated by Django 6.0.3 on 2026-04-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_customersession_screen_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
