# Generated by Django 6.0.3 on 2026-04-21 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_requests', '0002_alter_screenrequest_request_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screenrequest',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenrequest',
            name='played_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='played_screen_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='screenrequest',
            name='request_type',
            field=models.CharField(choices=[('running_text', 'Running Text'), ('vtron_text', 'Vtron Text'), ('vtron_photo', 'Vtron Photo'), ('vtron_video', 'Vtron Video')], max_length=25),
        ),
        migrations.AlterField(
            model_name='screenrequest',
            name='status',
            field=models.CharField(choices=[('pending_review', 'Pending Review'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('played', 'Played'), ('rejected', 'Rejected')], default='pending_review', max_length=20),
        ),
    ]
