# Generated by Django 6.0.3 on 2026-04-21 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_requests', '0003_screenrequest_played_at_screenrequest_played_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenrequest',
            name='payment_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
