# Generated by Django 6.0.3 on 2026-04-30 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('screen_requests', '0004_screenrequest_payment_link'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='screenrequest',
            name='billed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='screenrequest',
            name='billed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billed_screen_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='screenrequest',
            name='is_billed',
            field=models.BooleanField(default=False),
        ),
    ]
